In [55]:
import numpy as np

# 1 Softmax
### $\sigma(z_i)=\frac{e^{z_i}}{\sum_{j=0}^K e^{z_j}}$for $i=1,.....,K$ and $z=(z_1,....,z_k)\in R^k$

### Python Implementation

In [56]:
def softmax(L):
    exp_l = np.exp(L)
    return np.divide(exp_l, exp_l.sum())

### Usage

In [57]:
L = [5,6,7]
softmax(L)

array([0.09003057, 0.24472847, 0.66524096])

# 2 Sigmoid

### Python Implementation

In [58]:
# Activation (sigmoid) function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_v2(X):
    return np.divide(1, 1+np.exp(np.dot(-1, X)))

### Usage

In [59]:
X = np.array([-100, -10, 0, 10, 100])
sigmoid(X)

array([3.72007598e-44, 4.53978687e-05, 5.00000000e-01, 9.99954602e-01,
       1.00000000e+00])

# 3 Sigmoid derivtive

### Python Implementation

In [60]:
def sigmoid_prime(x):
    return sigmoid(x) * (1-sigmoid(x))

### Usage

# 4 Error

### Python Implementation

In [61]:
def error_formula(y, output):
    return y * np.log(output) + (1 - y) * np.log(1 - output)

### Usge

In [62]:
y=np.array([1])
error_formula(y,output)

array([-0.31326169])

# 5 Cross Etropy
### $Cross-Entropy= -\sum_{i=0}^n y_iln(p_i)+(1-y_i)ln(1-p_i)$

### Python Implementation

In [63]:
def cross_entropy(y, output):
    return -np.sum(error_formula(y, output))

def cross_entropy_v2(Y, P):
    Y = np.float_(Y)
    P = np.float_(P)
    return -np.sum(Y * np.log(P) + (1-Y) * np.log(1-P))

### Usage

In [64]:
Y=np.array([1,1,0])
p=np.array([0.8,0.7,0.1])
cross_entropy(Y,p) # Expected 0.69

0.6851790109107685

In [65]:
Y=[1,1,0]
p=[0.8,0.7,0.1]
cross_entropy_v2(Y,p) # Expected 0.69

0.6851790109107685

# 6 Prediction formula
$\hat{y}=\sigma(WX+b)=w_1x_1+w_2x_2+......+w_nx_n+b$

### Python Implementation

In [66]:
# Output (prediction) formula
def output_formula(features, weights, bias):
    y_hat = sigmoid(np.matmul(features,weights)+bias)
    return y_hat

### Usage

In [67]:
weights=[1,1]
features=[1,1]
bias=-1
output = output_formula(features, weights, bias)

In [68]:
# Gradient descent step
def update_weights(x, y, weights, bias, learnrate):
    y_hat = output_formula(x, weights, bias)
    error = y - y_hat
    weights = weights + learnrate * error * x
    bias = bias +  learnrate * error
    return weights, bias

In [69]:
x=np.array([1,1])
weights = np.random.normal(scale=1 / 2**.5, size=2)
y=np.array([1])
bias=1
update_weights(x,y,weights, bias, 0.001)

(array([ 0.03343474, -0.10830096]), array([1.00028403]))